# Datahub Assignments

This is a guide to submitting assignments on datahub.

## Overview  

**Technical Overview:**  Assignments are [jupyter notebooks](https://jupyter-notebook.readthedocs.io/en/stable/) served from UCSD's [datahub](https://datahub.ucsd.edu), and automatically graded by [nbgrader](https://nbgrader.readthedocs.io/en/stable/).     

**Practical Overview:**  To complete an assigment you will need to:    

1. **Log in to [datahub](https://datahub.ucsd.edu):**  If you are enrolled in the class, you should be able to log in using your UCSD credentials (username@ucsd.edu, and your password)    
2. **Launch this class environment:** select "PSYC193L 1 - Introduction to R..." and click "Launch Environment".   
3. **Fetch assignments:** click on the "Assignments" tab and click "Fetch" to download a particular assignment to your account.
4. **Open assignments:**  Click on assignment name in downloaded list to expand the assignment files, then click on the main file in the assignment to open the assignment notebook.
5. **Complete assignment** follow the instructions in the notebook and save regularly while working.
6. **Check your work:** re-read questions and instructions; restart kernel and rerun all cells; look over results; save.
7. **Submit:**  Back in the assignment list, click "validate"  to check that you are passing all visible tests (this will **NOT** mean the answers are correct!).  Once validated, click "Submit"!  You can submit multiple times up until the deadline (see cautionary note below).

## Cautionary Points:  

- **DO NOT**: change the name of this file, try to change, delete, or copy/paste, existing cells. You can make new cells if you'd like, but do not change the existing content.

- **You MUST submit the notebook to receive credit. We cannot grade assignments that have not been submitted.**

- You can submit at any time up until a deadline, but **we grade your most recent submission**. This means that **if you submit an updated notebook after the submission deadline, it will be marked as late**.

- We may have *hidden* tests for answers that will only run during official grading -- so make sure your code does what it is supposed to: passing visible tests is not sufficient for getting the right answer.

- Remember to **remove the** `fail() # No Answer` **line** in code cells you answer!

## Tips & Tricks

The following are a couple tips & tricks that may help you if you get stuck on anything.
  
- Consult the [debugging guide](debugging.md)

- **Print variables:** You can (and should) print and check variables as you go. This allows you to check what values they hold, what types they are, and fix things if anything unexpected happens.

- **Restart the Kernel:** If you run cells out of order, you can end up overwriting things in your namespace/global environment. If things seem to go weird, a good first step is to restart the kernel, which you can do from the kernel menu at the top of a notebook (also 'Restart & Run All' before submitting, to make everything runs properly in order).
